apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: multi-k8s-com-tls
spec:
  secretName: multi-k8s-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: multi-k8s.com
  dnsNames:
    - multi-k8s.com
    - www.multi-k8s.com
  acme:
    config:
      - http01:
        ingressClass: nginx
        domains:
          - multi-k8s.com
          - www.multi-k8s.com